### ISSUE TITLE
Huge thanks for your efforts & question

### ISSUE THREAD

**Issue by ph0enixph0enix** [rhasspy/piper-phonemize#10]
First of all: A huge thanks from my side for all your efforts.
This project is desperately needed! <3
I'm sitting on a Windows 10 64 bit machine and can't get Piper TTS to run just because of the phonemizer not able to instal via pip:

pip install piper-phonemize~=1.1.0
ERROR: Could not find a version that satisfies the requirement piper-phonemize~=1.1.0 (from versions: none)
ERROR: No matching distribution found for piper-phonemize~=1.1.0

As far as I've seen from your commit history, you've been working on it (which is great!). I would help if I would have the knowledge to do so.

My question:
It is not ready to use on Windows right now, am I right?
If there is a way (even with caveats) please let me know how I can get to run on my machine...

**Comment by raivisdejus** [comment]
pip encodes some package information in their file names, so if the relevant part of the file name does not match your system it will not install it. I was able to work around this issue on an older computer the following way:

1. Install any package and pay attention to the downloaded file names as those will be supported on your system.  
```
$ pip install piper-tts
Collecting piper-tts
  Using cached piper_tts-1.2.0-py3-none-any.whl.metadata (776 bytes)
```
Note the `py3-none-any` part of the filename.

2. Download a release file,  like `piper_phonemize-1.1.0-cp310-cp310-manylinux_2_28_x86_64.whl ` and change the `cp310-cp310-manylinux_2_28_x86_64` part in the file name to what you noted earlier. 

3. Use `pip install` and pass the new file to it.

This worked for me. Most likely there is a better more proper solution.

**Comment by eusthace811** [comment]
> pip encodes some package information in their file names, so if the relevant part of the file name does not match your system it will not install it. I was able to work around this issue on an older computer the following way:
> 
> 1. Install any package and pay attention to the downloaded file names as those will be supported on your system.
> 
> ```
> $ pip install piper-tts
> Collecting piper-tts
>   Using cached piper_tts-1.2.0-py3-none-any.whl.metadata (776 bytes)
> ```
> 
> Note the `py3-none-any` part of the filename.
> 
> 2. Download a release file,  like `piper_phonemize-1.1.0-cp310-cp310-manylinux_2_28_x86_64.whl ` and change the `cp310-cp310-manylinux_2_28_x86_64` part in the file name to what you noted earlier.
> 3. Use `pip install` and pass the new file to it.
> 
> This worked for me. Most likely there is a better more proper solution.

Thanks for this, I could install the packages now. Yet, I still can't get to run the piper http server.

'''
pip install "piper-tts==1.2.0" --no-cache-dir --force-reinstall --no-deps 
pip install onnxruntime-gpu flask 
pip install "piper_phonemize-1.1.0-py3-none-any.whl" --no-cache-dir --force-reinstall --no-deps
'''


'''
Traceback (most recent call last): File "<frozen runpy>", line 189, in _run_module_as_main File "<frozen runpy>", line 112, in _get_module_details File "C:\Users\...\Projects\piper\src\python_run\piper\__init__.py", line 1, in <module> from .voice import PiperVoice File "C:\Users\...\Projects\piper\src\python_run\piper\voice.py", line 10, in <module> from piper_phonemize import phonemize_codepoints, phonemize_espeak, tashkeel_run File "C:\Users\...\Projects\piper\env\Lib\site-packages\piper_phonemize\__init__.py", line 6, in <module> from piper_phonemize_cpp import ( ModuleNotFoundError: No module named 'piper_phonemize_cpp'
'''

**Comment by DrBill37** [comment]
I have the exact same error attempting to run piper after installing the renamed wheel on Windows, unable to import  'piper_phonemize_cpp':  No module named 'piper_phonemize_cpp'

It appears that setup.py is not finding the external modules:

ext_modules = [
    Pybind11Extension(
        "piper_phonemize_cpp",
        [
            "src/python.cpp",
            "src/phonemize.cpp",
            "src/phoneme_ids.cpp",
            "src/tashkeel.cpp",
        ],
        define_macros=[("VERSION_INFO", __version__)],
        include_dirs=[str(_ESPEAK_DIR / "include"), str(_ONNXRUNTIME_DIR / "include")],
        library_dirs=[str(_ESPEAK_DIR / "lib"), str(_ONNXRUNTIME_DIR / "lib")],
        libraries=["espeak-ng", "onnxruntime"],
    ),

**Comment by DoS007** [comment]
pip install piper-tts gives me ERROR: No matching distribution found for piper-phonemize~=1.1.0

**Comment by colafly** [comment]
not sure if it is still helpful, but the problem for me was because pybind11 is not installed, once i got that and also update espeak-ng location to correct path, i can run piper-phonemize without problem

**Comment by masterwang22327** [comment]
@colafly could you describe your solution with more details？i using the pull request#43, meet the same error no module named piper_phonemize_cpp.
1.should i install pybind11 in Dockerfile,so that setup.py can run successful.
2.how to find espeak-ng location?i konw that apt install espeak-ng can install espeak-ng,but the location and file is not same as setup.py

![Image](https://github.com/user-attachments/assets/bbb9988a-ed1b-4b18-bd00-7a8747726d1d)

**Comment by csukuangfj** [comment]
Please see https://github.com/rhasspy/piper-phonemize/issues/46#issuecomment-2999016143
